/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.LoginStuff.login;
import com.mycompany.excelstuff.ExcelStuff;
import com.Adminpackage.Admin.*; 
import javax.swing.*;
import com.Globalstuff.Global;
/**
 *
 * @author Sarel
 */
public class LoginStuff extends javax.swing.JFrame {
   
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginStuff.class.getName());

    /**
     * Creates new form LoginStuff
     */
    public LoginStuff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtUsuarioname = new java.awt.TextField();
        CKShowPw = new javax.swing.JCheckBox();
        TxtPassWord = new javax.swing.JPasswordField();
        BtnSalir = new javax.swing.JButton();
        BtnEntrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(TxtUsuarioname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 330, 30));

        CKShowPw.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        CKShowPw.setForeground(new java.awt.Color(0, 0, 0));
        CKShowPw.setText("Mostrar contraseña");
        CKShowPw.setContentAreaFilled(false);
        CKShowPw.addActionListener(this::CKShowPwActionPerformed);
        getContentPane().add(CKShowPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        TxtPassWord.setBackground(new java.awt.Color(255, 255, 255));
        TxtPassWord.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(TxtPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 330, 30));

        BtnSalir.setBackground(new java.awt.Color(255, 0, 0));
        BtnSalir.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(0, 0, 0));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(this::BtnSalirActionPerformed);
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 80, 40));

        BtnEntrar.setBackground(new java.awt.Color(51, 255, 51));
        BtnEntrar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        BtnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnEntrar.setText("Entrar");
        BtnEntrar.addActionListener(this::BtnEntrarActionPerformed);
        getContentPane().add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 80, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Github\\AsistanciasPlanillasandSuch\\ExcelStuff\\src\\main\\java\\imagenes\\png_de_logo350x80.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 350, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Github\\AsistanciasPlanillasandSuch\\ExcelStuff\\src\\main\\java\\imagenes\\Icono perfil Azul n 105x105.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 105, 105));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Github\\AsistanciasPlanillasandSuch\\ExcelStuff\\src\\main\\java\\imagenes\\icono candado105x105.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 105, 105));

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Usuario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Github\\AsistanciasPlanillasandSuch\\ExcelStuff\\src\\main\\java\\imagenes\\Fondo_FormularioAsistenciaPermiso.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        ExcelStuff obj = new ExcelStuff(); 
        
        char[] PassArray = TxtPassWord.getPassword();
        String UserName = TxtUsuarioname.getText(), Password = new String(PassArray);
        String ID_String;
        int ID_Verificacion = -1, ID_Empleado; //Siempre tiene un valor -1 si los usuarios no son verificables
        ID_Verificacion = obj.verificar_usuarios(UserName, Password); 
        ID_Empleado = obj.ID_EmpleadoLogin(UserName, Password);
        if(ID_Verificacion == -1){
            JOptionPane.showMessageDialog(null, "El usuario o la contraseña es incorrecta. Intente de nuevo");
            TxtPassWord.setText("");
        }else if (ID_Verificacion == 1) {
             Principal menu = new Principal();
             menu.setTitle ("Sistema de Usuario");
             menu.setLocationRelativeTo (null);
             menu.setVisible(true);
             ID_String = Integer.toString(ID_Empleado);
             obj.WriteExcelFile("Usuarios", 6, 8,ID_String, "General" );
             dispose();
        }else{
             ID_String = Integer.toString(ID_Empleado);
             
            obj.WriteExcelFile("Usuarios", 6, 8,ID_String, "General" ); //ocupamos varias formas para que el usuario se registre en una variable "Global" pero cualquier intento fue muy complicado. 
            Principalv2 menuv2 = new Principalv2();
            menuv2.setTitle ("Sistema de Administración");
            menuv2.setLocationRelativeTo (null);
            menuv2.setVisible(true);
            dispose();
        };
        
        
        
    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        dispose();
        
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void CKShowPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CKShowPwActionPerformed
        if (CKShowPw.isSelected()){
            System.out.println("TRUE!");
            TxtPassWord.setEchoChar((char)0);
        }else{
            System.out.println("False!");
            TxtPassWord.setEchoChar('*');
        }
    }//GEN-LAST:event_CKShowPwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginStuff().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JCheckBox CKShowPw;
    private javax.swing.JPasswordField TxtPassWord;
    private java.awt.TextField TxtUsuarioname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
